name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Run Cucumber Regression
      run: npm run cucumberRegression
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-and-cucumber-report
        path: |
          playwright-report/
          cucumber-report.html
        retention-days: 30
